name: Test PowerShell
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: ./Libsync.ps1 -ClientId '$CLIENT_ID' -ClientSecret '${{ secrets.CLIENT_SECRET }}' -TenantId '$TENANT_ID'
