name: Live Response Tools Sync
on: push

jobs:
  sync-job:
    name: main 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Execute sync script
        shell: pwsh
        run: ./Libsync.ps1 -ClientId '${{ vars.CLIENT_ID }}' -ClientSecret '${{ secrets.CLIENT_SECRET }}' -TenantId '${{ vars.TENANT_ID }}'
