name: Test PowerShell
on: push

jobs:
  pester-test:
    name: test step
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform powershell
        shell: pwsh
        run: ./Libsync.ps1 -ClientId '${{ vars.CLIENT_ID }}' -ClientSecret '${{ secrets.CLIENT_SECRET }}' -TenantId '${{ vars.TENANT_ID }}'
